Manually merged release-0.4.1 branch and 27-new-caching-solution.
TU-Wien-dataLAB/Grader-Labextension pull request #46
Opened 2024-05-01 10:37 UTC by mpetojevic

`27-react-query-caching` contains all changes from [27-new-caching-solution](https://github.com/TU-Wien-dataLAB/Grader-Labextension/tree/27-new-caching-solution). I had to manually merge my old branch with `release-0.4.1` due to modifications in file selection for pushing, not present in the original `27-new-caching-solution` branch, leading to many conflicts. In the  `27-react-query-caching`changes from `release-0.4.1`  and `27-new-caching-solution` are integrated.

Ref: #27

2024-05-06 12:14 UTC, meffmadd commented on package.json
> +        "@tanstack/react-query-devtools": "^5.27.8",
react-query-devtools hört sich nach dev dependency an

2024-05-06 12:34 UTC, meffmadd commented on src/components/coursemanage/grading/edit-submission.tsx
> +              {logs}
Könnte man umbschrieben in `{logs | "No logs available"}` dann spart man sich den zweiten Typography tag

2024-05-06 15:00 UTC, meffmadd requested changes
The implementation looks very clean!

2 points:
- I don't think caching is configured correctly. The reason we wanted to switch to Tanstack Query is to have client-side caching. When I go to the coursemanage view, click on a lecture, go back, click on the same lecture again, etc., there are always requests made through the request service. I think the `staleTime` has to be set to be `>0`?
- We can then remove the current HTTP browser-based caching by removing the `@cache` decorator from the tornado handler functions.

2024-05-07 11:21 UTC, florian-jaeger requested changes
Good job! I experienced the redundant data fetching as well that @meffmadd pointed out.

2024-07-03 13:41 UTC, merged